// Plain-English definitions for the jargon GRQ puts on screen. The financial-
// literacy pillar (docs/LITERACY.md): every term should be explainable on the
// spot. Keys are lowercase slugs the <Term> component looks up. Static seed for
// the app's own vocabulary; agent-generated explainers for novel concepts come later.

// `example` is a one-line "here's what that looks like" sentence; `related` is a
// list of other glossary slugs a reader would naturally jump to. Both optional —
// older entries (and the bundled iOS subset) decode fine without them. Surfaced on
// The Wire's lesson cards (Phase 2: literacy richness) and the in-app explainer.
export type GlossaryEntry = { term: string; def: string; example?: string; related?: string[] };

export const GLOSSARY: Record<string, GlossaryEntry> = {
  nav: {
    term: "NAV — Net Asset Value",
    def: "The fund's total worth right now: cash plus the market value of everything it holds.",
    example: "If GRQ holds $18,000 of stock and $7,000 of cash, its NAV is $25,000.",
    related: ["market-value", "drawdown", "contributions"],
  },
  acb: {
    term: "ACB — Adjusted Cost Base",
    def: "Your average cost per share, commissions included. The CRA uses it to figure your capital gain when you sell.",
    example: "Buy 10 shares at $20 plus a $5 commission and your ACB is $20.50 a share.",
    related: ["commission", "unrealized-pnl", "superficial-loss"],
  },
  "day-pnl": {
    term: "Day P&L",
    def: "How much the fund's value moved today — in dollars and percent — versus where it opened this morning.",
    example: "Open at $25,000, sit at $25,300 by lunch, and the day P&L is +$300 (+1.2%).",
    related: ["the-tape", "total-pnl", "nav"],
  },
  "total-pnl": {
    term: "Total P&L",
    def: "Profit or loss since day one: current NAV minus every dollar ever contributed.",
    example: "Contribute $25,000 over time, sit at a $28,000 NAV, and your total P&L is +$3,000.",
    related: ["contributions", "vs-xic", "day-pnl"],
  },
  "vs-xic": {
    term: "vs XIC — the benchmark",
    def: "What your contributions would be worth if you'd just bought XIC, an ETF holding the whole TSX. Beating it is the bar GRQ has to clear to justify existing.",
    example: "If GRQ is up 6% while XIC is up 9%, the fund is losing to the couch-potato option — by 3 points.",
    related: ["etf", "contributions", "total-pnl"],
  },
  drawdown: {
    term: "Drawdown",
    def: "How far NAV has fallen from its highest point. Hit −15% and the kill switch trips automatically.",
    example: "NAV peaks at $30,000 then dips to $27,600 — that's an −8% drawdown.",
    related: ["nav", "kill-switch", "stop-loss"],
  },
  "kill-switch": {
    term: "Kill switch",
    def: "A hard stop, enforced in code, that halts all trading instantly. Either member can flip it; nothing trades while it's engaged.",
    example: "Flip it before a volatile earnings print and no order can leave the gate until you flip it back.",
    related: ["drawdown", "soak"],
  },
  "cash-floor": {
    term: "Cash floor",
    def: "The minimum share of NAV that must stay in cash, so the fund is never fully committed. Set by the risk dial.",
    example: "A 20% cash floor on a $25,000 fund keeps at least $5,000 in cash — dry powder the gate won't let it spend.",
    related: ["nav", "weight", "kill-switch"],
  },
  "superficial-loss": {
    term: "Superficial-loss rule",
    def: "A CRA rule: sell at a loss and rebuy the same name within 30 days and the loss is denied. The agent is barred from tripping it.",
    example: "Sell XYZ at a loss Monday, rebuy it Friday, and the CRA throws the loss out — you wasted the tax break.",
    related: ["capital-gains", "acb"],
  },
  "round-trip": {
    term: "Round-trip cost",
    def: "Commission to buy plus commission to sell. A trade has to be worth at least 3× this to be allowed — fees are the enemy of a small account.",
    example: "Two $5 commissions = a $10 round trip, so GRQ won't take the trade unless it expects to clear at least $30.",
    related: ["commission", "fee-budget"],
  },
  rsi: {
    term: "RSI — Relative Strength Index",
    def: "A 0–100 momentum gauge. Below 30 is 'oversold' (maybe due for a bounce), above 70 'overbought'. An input, not a verdict.",
    example: "A name selling off to RSI 24 is 'oversold' — stretched low, but cheap-and-falling is still falling.",
    related: ["macd", "trend", "recommendation"],
  },
  macd: {
    term: "MACD",
    def: "Moving Average Convergence Divergence — tracks whether short-term momentum is pulling ahead of, or falling behind, the longer trend.",
    example: "When MACD crosses above its signal line, short-term momentum just turned up — a bullish nudge, not a verdict.",
    related: ["rsi", "sma", "trend"],
  },
  sma: {
    term: "SMA — Simple Moving Average",
    def: "The average closing price over the last N days (SMA50 ≈ 10 weeks). Smooths out daily noise to show the underlying trend.",
    example: "A stock bouncing off its rising 50-day SMA is often read as the uptrend holding.",
    related: ["trend", "macd"],
  },
  trend: {
    term: "Trend (SMA stack)",
    def: "Up- or down-trend read from the moving averages: price above its 50-day average, and the 50-day above the 200-day, is the classic 'uptrend' stack.",
    example: "Price > 50-day > 200-day is the textbook uptrend; flip the order and it's a downtrend.",
    related: ["sma", "macd", "recommendation"],
  },
  volatility: {
    term: "Volatility (realized)",
    def: "How much the price swings, annualized from the last ~20 days — a regime gauge (calm / normal / spicy), not a buy/sell signal. It tells you how bumpy the ride is.",
    example: "A biotech that swings 6% a day is high-volatility — bigger gains, bigger gut-checks — vs a utility that barely moves.",
    related: ["stop-loss", "short-interest"],
  },
  recommendation: {
    term: "Recommendation",
    def: "A confidence-weighted consensus of the directional signals (trend, rsi, macd). The % is the share of signal-confidence behind the call — advisory, not the agent's decision.",
    example: "A 70% recommendation means most of the signal-confidence leans one way — GRQ still makes the actual call.",
    related: ["rsi", "macd", "trend"],
  },
  dossier: {
    term: "Dossier",
    def: "A deep research write-up the agent files on one stock: the business, recent news, signals, bull and bear case, and a verdict.",
    example: "Before GRQ can buy a name, it files a dossier — business, catalysts, the bear case, a verdict — so the trade has receipts.",
    related: ["price-target", "agent-call", "recommendation"],
  },
  soak: {
    term: "Soak",
    def: "The trial run: the fund must trade clean for 4+ weeks (2 of them on real broker paper) before a single real dollar is at risk.",
    example: "Four clean weeks (two on IBKR paper) with no blown guardrails before real money — the soak is GRQ proving itself first.",
    related: ["kill-switch", "drawdown"],
  },
  contributions: {
    term: "Contributions",
    def: "Every dollar Cam and Graham have put into the fund. Total P&L and the benchmark are both measured against this — it's the money that had to be beaten.",
    example: "Put in $25,000 total and that's the bar both Total P&L and the XIC benchmark are measured against.",
    related: ["total-pnl", "vs-xic", "nav"],
  },
  "fee-budget": {
    term: "Fee budget",
    def: "A hard monthly ceiling on commissions. The order gate rejects any trade that would push this month's fees over the line — fees quietly kill small accounts.",
    example: "Hit the month's commission ceiling and the gate blocks the next trade until next month — fees can't snowball.",
    related: ["commission", "round-trip"],
  },
  "market-value": {
    term: "Market value",
    def: "What a holding is worth right now: shares held × the latest price. Add them all up, plus cash, and you get NAV.",
    example: "100 shares at $30 = $3,000 of market value; sum every holding plus cash and you have NAV.",
    related: ["nav", "position", "weight"],
  },
  "unrealized-pnl": {
    term: "Unrealized P&L",
    def: "Paper profit or loss on a holding you still own — what you'd lock in if you sold at the current price. It isn't real until you sell.",
    example: "Up $400 on a stock you still hold is unrealized — a paper gain that vanishes if the price falls before you sell.",
    related: ["acb", "market-value", "take-profit"],
  },
  weight: {
    term: "Weight",
    def: "How much of the fund one position is, as a share of NAV. The risk dial caps it so no single name can sink the whole boat.",
    example: "A $5,000 position in a $25,000 fund is a 20% weight — the risk dial caps how big any one name can get.",
    related: ["position", "nav", "drawdown"],
  },
  position: {
    term: "Position",
    def: "A holding: the shares of one stock the fund currently owns, with an average cost and a current value.",
    example: "50 shares of XIC at an average cost of $56 is a position — shares, a cost base, and a live value.",
    related: ["acb", "weight", "market-value"],
  },
  "market-cap": {
    term: "Market cap",
    def: "A company's total stock-market value: share price × shares outstanding. Roughly what it would cost to buy the whole company.",
    example: "A $40 stock with 50 million shares out has a $2-billion market cap — a small-cap.",
    related: ["pe", "market-value", "free-cash-flow"],
  },
  "free-cash-flow": {
    term: "Free cash flow",
    def: "The cash a business actually generates after running costs and reinvestment — money it's free to return to owners or stockpile. Harder to fake than reported earnings.",
    example: "A company can report a paper profit yet burn cash — negative free cash flow is the tell.",
    related: ["pe", "dividend-yield", "moat"],
  },
  "dividend-yield": {
    term: "Dividend yield",
    def: "The annual dividend as a percent of the share price. A $2 dividend on a $50 stock yields 4%.",
    example: "That same $2 dividend yields 5% if the stock falls to $40 — a high yield can flag a falling price.",
    related: ["free-cash-flow", "market-cap"],
  },
  "short-interest": {
    term: "Short interest",
    def: "The share of a stock that traders have borrowed and sold, betting it falls. High short interest signals bearishness — and can fuel a sharp 'short squeeze' if the price rises instead.",
    example: "20% of the float sold short, then good news hits — shorts scramble to buy back and the price rockets.",
    related: ["dilution", "volatility"],
  },
  dilution: {
    term: "Dilution",
    def: "When a company issues new shares, each existing share owns a smaller slice. Common with cash-hungry small-caps — it can quietly erode your stake even as the business grows.",
    example: "A cash-strapped miner doubles its share count to raise money — your slice of the company just halved.",
    related: ["market-cap", "short-interest"],
  },
  "stop-loss": {
    term: "Stop-loss",
    def: "A pre-set exit: if a holding falls to this price, the agent sells to cap the damage. The level is set by the risk dial (e.g. −8% on Balanced).",
    example: "Buy at $20 with an −8% stop and the agent auto-sells near $18.40 if it rolls over.",
    related: ["take-profit", "drawdown", "swing-trade"],
  },
  "take-profit": {
    term: "Take-profit",
    def: "The mirror of a stop: a pre-set level where the agent banks a winner so a paper gain doesn't evaporate. Also set by the risk dial.",
    example: "A +20% take-profit on that $20 entry banks the win near $24 instead of round-tripping it.",
    related: ["stop-loss", "expected-return", "price-target"],
  },
  "expected-return": {
    term: "Expected return",
    def: "The upside the agent's price target implies from today's price — a hypothesis with a horizon, not a promise. The track record builds as targets resolve.",
    example: "A $30 target on a $24 stock is a +25% expected return — if the thesis plays out.",
    related: ["price-target", "take-profit"],
  },
  "price-target": {
    term: "Price target",
    def: "Where the agent thinks a stock could trade — a near-term swing target and a 12-month view. The basis for expected return, judged honestly when it plays out.",
    example: "GRQ might post a near-term target of $26 and a 12-month target of $34 on the same name.",
    related: ["expected-return", "dossier", "swing-trade"],
  },
  commission: {
    term: "Commission",
    def: "The broker's fee per trade. Small but relentless: GRQ won't take a trade unless it's worth at least 3× the round-trip commissions.",
    example: "At ~$5 a trade, churning a $200 position to scalp 2% loses money to fees — exactly what the 3× rule blocks.",
    related: ["round-trip", "fee-budget"],
  },
  moat: {
    term: "Economic moat",
    def: "A durable advantage that protects a company's profits from competitors — brand, network effects, low costs, switching costs. Wide moats compound for years.",
    example: "Switching your whole company off one software suite is painful — that friction is the vendor's moat.",
    related: ["free-cash-flow", "pe"],
  },
  pe: {
    term: "P/E — Price-to-Earnings",
    def: "Share price divided by annual earnings per share — how many years of current profit you're paying for. High P/E = the market expects growth; low = skepticism or value.",
    example: "A $50 stock earning $2.50 a share trades at a P/E of 20 — twenty years of today's profit.",
    related: ["market-cap", "free-cash-flow", "moat"],
  },
  eps: {
    term: "EPS — Earnings Per Share",
    def: "A company's profit divided by its shares — the per-share slice of what it earned that quarter. Analysts publish an estimate beforehand; the reported actual beating or missing it is what usually moves the stock.",
    example: "Estimate $1.20, reports $1.35 → a beat. The market often cares more about the beat/miss than the raw number.",
    related: ["pe", "earnings"],
  },
  earnings: {
    term: "Earnings report",
    def: "A company's quarterly scorecard — revenue, profit, and EPS for the last three months, plus its outlook. Filed before the open (BMO) or after the close (AMC), it's the single biggest scheduled event for a stock.",
    example: "MU and AMD both reported after the close — the reaction shows up in the next session's price.",
    related: ["eps", "pe"],
  },
  etf: {
    term: "ETF — Exchange-Traded Fund",
    def: "A basket of stocks bought as one ticker. XIC, for instance, holds the whole TSX — instant diversification in a single trade.",
    example: "One share of XIC gives you a slice of every big Canadian company at once.",
    related: ["vs-xic", "market-cap"],
  },
  "swing-trade": {
    term: "Swing trade",
    def: "Holding for days to a few weeks to catch a price 'swing' — longer than day-trading, shorter than buy-and-hold. GRQ's core style.",
    example: "Buy a breakout, aim to sell into strength two or three weeks later — a swing, not a day-trade or a forever-hold.",
    related: ["the-tape", "tfsa", "price-target"],
  },
  confidence: {
    term: "Confidence",
    def: "How sure the agent (or a signal) is about a call, 0–100. A self-assessment, not a probability — and the agent needs ≥75% conviction before the gate will let it buy.",
    example: "The agent can like a name at 60%, but the gate won't let it buy until conviction clears 75%.",
    related: ["recommendation", "agent-call", "dossier", "confidence-levers"],
  },
  "confidence-levers": {
    term: "What would change our mind",
    def: "The specific, falsifiable things that would reframe Alfred's call — what's pinning the confidence below 100. Each is either a gap we could close (info that exists but we don't have — read the latest filing, no guidance feed) or a catalyst still to land (an event on a known date — earnings, a ruling). It says which way resolving it would move the call, how much, and how we'd learn it.",
    example: "A name might be a Hold only because earnings are two weeks out and would confirm or kill the margin thesis — once they land, the call gets re-rated.",
    related: ["confidence", "agent-call", "dossier"],
  },
  "the-tape": {
    term: "The Tape",
    def: "The fund's value through the trading day, open to now — the intraday line of NAV. (Old trading-floor slang: the ticker 'tape' that printed live prices.)",
    example: "If the Tape is down 1.2% at noon, the fund's NAV has slipped 1.2% since this morning's open.",
    related: ["nav", "day-pnl"],
  },
  "agent-call": {
    term: "Alfred's call",
    def: "GRQ's own judgment on a name — buy, accumulate, hold, watch, trim, avoid, or sell — weighing the business, the news, and the price. Distinct from the signal consensus (a technicals formula); when the two disagree, the 'why' below explains it.",
    example: "GRQ can rate a name 'accumulate' even while the technical signal reads neutral — the 'why' explains the gap.",
    related: ["recommendation", "dossier", "price-target"],
  },
  universe: {
    term: "The universe",
    def: "The list of stocks the agent is allowed to buy. A name joins by being promoted — any member (or the agent itself, under code-enforced rules) can promote a researched candidate once it clears an automated liquidity screen. Only then can the agent buy it, and every order still clears the order gate.",
    example: "A name has to clear the liquidity screen to enter the universe — only then can the agent buy it; until then it's a candidate.",
    related: ["watchlist", "kill-switch"],
  },
  watchlist: {
    term: "Watchlist",
    def: "The names you're watching — your personal interest list. Each member's watches stack up as faces on a name, and the agent researches every watched name (a dossier, signals, its call). Watching is separate from the universe: a name stays on your watchlist even after it's promoted, and the agent still can't trade it until it's in the universe.",
    example: "Cam and Graham can both watch the same name — you'll see both faces — and GRQ researches it; it can't trade it until it's promoted into the universe.",
    related: ["universe", "agent-call"],
  },
  "analyst-target": {
    term: "Analyst consensus target",
    def: "The average 12-month price target from the Wall Street analysts who cover the stock. A useful outside check on Alfred's call — when GRQ and the street sharply disagree, it's worth asking who's right.",
    example: "If the street's average target is $40 and GRQ's is $28, someone's wrong — worth knowing why before you buy.",
    related: ["price-target", "expected-return"],
  },
  "capital-gains": {
    term: "Capital gains tax",
    def: "Tax on the profit when you sell for more than you paid. In Canada (non-registered accounts), half the gain is taxable at your marginal rate — so a 10% gain is worth less after tax. Inside a TFSA, gains are tax-free.",
    example: "Sell for a $1,000 gain in a non-registered account and ~$500 is taxable at your rate; in a TFSA the whole $1,000 is yours.",
    related: ["tfsa", "superficial-loss", "rrsp"],
  },
  tfsa: {
    term: "TFSA — Tax-Free Savings Account",
    def: "A registered account where investment gains are tax-free. The catch: trade too actively and the CRA can reclassify it as a business and tax everything — so a swing-trade cadence (not day-trading) matters.",
    example: "Day-trade inside a TFSA and the CRA can call it a business and tax it all — a swing cadence keeps it tax-free.",
    related: ["swing-trade", "capital-gains", "rrsp"],
  },
  rrsp: {
    term: "RRSP — Registered Retirement Savings Plan",
    def: "A registered account: contributions reduce this year's taxable income and growth is tax-deferred — you pay tax as income when you withdraw in retirement.",
    example: "A $5,000 RRSP contribution lowers this year's taxable income; you pay tax later, as income, when you draw it down.",
    related: ["tfsa", "capital-gains"],
  },
  "13f": {
    term: "13F filing",
    def: "A quarterly report big investment managers (over $100M) must file listing their U.S. stock holdings. It's a snapshot, filed up to ~45 days after quarter-end, and it shows only longs and options — never short positions.",
    example: "Buffett's Q1 13F landing in mid-May shows what Berkshire held back in March — useful colour, stale for timing.",
    related: ["qoq", "form-4", "put-option"],
  },
  qoq: {
    term: "QoQ — quarter over quarter",
    def: "The change from one quarter (a three-month reporting period) to the next. Here, '+24 QoQ' means 24 more institutions hold the stock than in the previous quarter's 13F filings — a measure of whether big money is building or trimming the position.",
    example: "'+24 QoQ' means 24 more institutions hold the name than last quarter — big money building the position.",
    related: ["13f", "insider"],
  },
  "form-4": {
    term: "Form 4 — insider trade",
    def: "The filing a company's executives, directors, and 10%+ owners must submit within two days of trading its stock. Open-market purchases are the meaningful 'insider buying' signal; option exercises and grants are noise.",
    example: "A CEO buying $250k of her own stock on the open market files a Form 4 — that's the buy worth noticing.",
    related: ["insider", "cluster-buying"],
  },
  insider: {
    term: "Insider",
    def: "A company's own officers, directors, or 10%+ owners. Their trades are disclosed on Form 4 — when they buy on the open market with their own money, it's often read as confidence in the business.",
    example: "When three insiders buy with their own cash the same week, it's often read as real confidence in the business.",
    related: ["form-4", "cluster-buying"],
  },
  "put-option": {
    term: "Put (option)",
    def: "A bet that a stock falls — it gains value as the price drops. In a 13F a put shows up as a 'holding', but it's a bearish position, not ownership of the shares.",
    example: "A put line in a 13F isn't ownership — it's a bet the stock falls, so don't read it as a vote of confidence.",
    related: ["call-option", "13f"],
  },
  "call-option": {
    term: "Call (option)",
    def: "A leveraged bet that a stock rises — it gains value as the price climbs. A call line in a 13F is a bullish add-on, not plain share ownership.",
    example: "A fund adding calls on a name is leaning bullish with leverage — a louder version of buying the shares.",
    related: ["put-option", "13f"],
  },
  "cluster-buying": {
    term: "Cluster buying",
    def: "Several different insiders at one company buying its stock around the same time — a stronger signal than any single purchase, since it's harder to dismiss as one person's hunch.",
    example: "One director buying is a shrug; five insiders buying the same week is a cluster — much harder to dismiss.",
    related: ["insider", "form-4"],
  },
  "congress-trade": {
    term: "Congressional disclosure",
    def: "Members of Congress must disclose their stock trades — but only as dollar ranges (e.g. $1M–$5M) and up to ~45 days late. Colour on what well-connected people are doing, not a holdings list and not a timing signal.",
    example: "A disclosure might read '$1M–$5M, filed 40 days late' — colour on the well-connected, not a holdings list or a timing signal.",
    related: ["13f", "insider"],
  },

  // ---- The Race: the AI models in GRQ's bake-off (docs/THE-RACE.md) ----
  llm: {
    term: "LLM — Large Language Model",
    def: "An AI trained on vast amounts of text to read, reason, and write. GRQ's agent is an LLM; The Race pits several different ones against the same market data.",
    example: "Ask one 'should we buy XIC today?' and it works through the fund's data like an analyst would.",
    related: ["the-race", "opus"],
  },
  "the-race": {
    term: "The Race — GRQ's model bake-off",
    def: "Each session the same data is handed to several AI models. Only Opus (the 'champion') actually trades; the rest are 'shadow' challengers that just say what they'd do — so we can score who's right without risking a dollar.",
    example: "At a 1pm check-in Opus buys SHOP while Grok would've held — both calls get logged and marked to the live price.",
    related: ["llm", "opus", "vs-xic"],
  },
  opus: {
    term: "Claude Opus 4.8 — the champion",
    def: "Anthropic's most capable model, and the ONLY one in The Race that places real trades. Every other model is shadow-only.",
    example: "When GRQ actually buys something, it was Opus's call that cleared the gate.",
    related: ["the-race", "sonnet", "llm"],
  },
  sonnet: {
    term: "Claude Sonnet 4.6",
    def: "Anthropic's faster, lighter Claude. A shadow challenger in The Race — it proposes, never trades — and runs free on the fund's existing Claude plan.",
    example: "Sonnet might back Opus's buy, or argue it'd wait for a cleaner entry.",
    related: ["opus", "the-race", "haiku"],
  },
  haiku: {
    term: "Claude Haiku 4.5",
    def: "Anthropic's smallest, quickest Claude. GRQ uses it for cheap triage — deciding whether a news event is even worth a full analysis — not for trade decisions.",
    example: "A routine headline? Haiku says 'ignore' so the expensive model never has to wake up.",
    related: ["opus", "sonnet", "llm"],
  },
  gpt: {
    term: "GPT-5.1 — OpenAI",
    def: "OpenAI's flagship model, racing shadow-only. A different lineage from Claude, so it's a genuinely independent second opinion.",
    example: "Reading the same data, GPT-5.1 might rank a different name as the day's best setup.",
    related: ["the-race", "gemini", "llm"],
  },
  gemini: {
    term: "Gemini 3.1 Pro — Google",
    def: "Google's flagship model, racing shadow-only. It 'reasons' visibly before answering — thorough, but the priciest challenger to run.",
    example: "Gemini may spend a paragraph weighing both sides before settling on HOLD.",
    related: ["the-race", "gpt", "llm"],
  },
  glm: {
    term: "GLM-4.6 — Z.ai",
    def: "An open-weight model from Chinese lab Z.ai (Zhipu). A shadow challenger — strong reasoning at a fraction of the frontier price.",
    example: "GLM-4.6 costs a fraction of the frontier models per call yet still makes a credible call.",
    related: ["deepseek", "the-race", "llm"],
  },
  deepseek: {
    term: "DeepSeek V3 — DeepSeek",
    def: "An open-weight model from Chinese lab DeepSeek, known for near-frontier quality at a tiny price. The cheapest challenger in The Race.",
    example: "DeepSeek weighs in on every session for cents a day.",
    related: ["glm", "the-race", "llm"],
  },
  grok: {
    term: "Grok 4.3 — xAI",
    def: "The model from Elon Musk's xAI, and a shadow challenger — it rounds out the field so all four major frontier labs are represented.",
    example: "Grok 4.3 gets the exact same prompt as Opus and logs what it would have done.",
    related: ["the-race", "gpt", "llm"],
  },
  llama: {
    term: "Llama 4 Maverick — Meta",
    def: "Meta's open-weight model and the most widely self-run open model in the West. A shadow challenger — a different lineage again from the frontier labs and the Chinese open-weights.",
    example: "Reading the same data as Opus, Llama logs the call it would have made.",
    related: ["deepseek", "glm", "the-race"],
  },
  "options-positioning": {
    term: "Options positioning",
    def: "What the options market reveals about how big traders are betting on a stock. GRQ never trades options — it reads this only as a signal about the underlying stock (where the crowd and the dealers are leaning).",
    example: "Heavy put buying + dealers positioned to amplify moves can flag a name the market is bracing on.",
    related: ["gamma-exposure", "put-call-ratio", "implied-volatility"],
  },
  "gamma-exposure": {
    term: "Dealer gamma (GEX)",
    def: "Market-makers who sold the options must constantly buy/sell the stock to stay hedged. When net gamma is POSITIVE they trade AGAINST moves → the stock gets 'pinned' / range-bound. When NEGATIVE they trade WITH moves → swings get amplified and trendy.",
    example: "Negative gamma into a selloff means dealers keep selling as it drops — the move feeds on itself.",
    related: ["call-wall", "put-wall", "options-positioning"],
  },
  "put-call-ratio": {
    term: "Put/Call ratio",
    def: "Puts divided by calls (by open interest or today's volume). Above 1 = more puts → defensive / bearish lean or hedging; below 1 = call-heavy → bullish or speculative. A crowd-positioning gauge, best read as a contrarian extreme.",
    example: "A put/call of 1.9 on the day means heavy defensive put flow.",
    related: ["options-positioning", "volatility-skew"],
  },
  "implied-volatility": {
    term: "Implied volatility (IV)",
    def: "The size of move the options market is PRICING IN over the next ~month, as an annualized %. High IV = the market expects big swings (fear or a catalyst); low IV = calm expected. It's the market's forecast, not a fact.",
    example: "50% IV on a stock means options are priced for a much wilder ride than one at 20%.",
    related: ["volatility-skew", "options-positioning"],
  },
  "call-wall": {
    term: "Call wall / Put wall",
    def: "The strike prices where dealer hedging is heaviest. The call wall often acts like a ceiling/magnet (resistance); the put wall like a floor (support). Not guarantees — just where options-driven hedging concentrates.",
    example: "A call wall at $400 can cap a rally as dealers sell into it to stay hedged.",
    related: ["gamma-exposure"],
  },
  "volatility-skew": {
    term: "Volatility skew (25Δ)",
    def: "How much more the market pays for downside protection (out-of-the-money puts) than upside (calls), in basis points. A high positive skew = the market is bidding up crash insurance → fear; flat/low skew = complacency.",
    example: "A 200bp skew means puts are notably 'fearful' versus calls — the market's paying up for protection.",
    related: ["implied-volatility", "put-call-ratio"],
  },
  "social-buzz": {
    term: "Social buzz (0–100)",
    def: "GRQ's own loudness score for a name on retail forums — how much it's being talked about (Reddit mention volume) and whether that's accelerating. High buzz isn't a buy signal; on a name we hold it's a CROWDING/risk flag (euphoria can reverse hard). A signal we weigh, never a trade.",
    example: "A holding spiking to buzz 90 means the crowd has piled in — watch for a blow-off, not a green light.",
    related: ["mention-velocity", "social-sentiment"],
  },
  "mention-velocity": {
    term: "Mention velocity",
    def: "Today's Reddit mentions for a name divided by its own trailing 7-day average. Above 1 = chatter is heating up; below 1 = cooling off. We measure it against the name's OWN history so a normally-quiet stock suddenly lighting up stands out.",
    example: "2.0× means twice the usual daily chatter — something just grabbed retail's attention.",
    related: ["social-buzz", "social-sentiment"],
  },
  "social-sentiment": {
    term: "Social sentiment",
    def: "The share of retail posts tagged bullish vs bearish (from Stocktwits, where users self-label each message). Noisy and easily gamed — GRQ reads it as crowd mood, not truth, and it earns trust slowly like any source. The fund never trades on it alone.",
    example: "85% bullish on a name the crowd already owns can mean the easy money's been made.",
    related: ["social-buzz", "mention-velocity"],
  },

  // ---- Options literacy: the calculator + education portal (docs/OPTIONS-PORTAL.md) ----
  strike: {
    term: "Strike price",
    def: "The fixed price written into an option contract. A call only pays off when the stock is ABOVE its strike; a put only when it's BELOW. It's the line in the sand the whole bet is measured against.",
    example: "A $105 call on a $100 stock needs the price above $105 by expiry to have any value left.",
    related: ["call-option", "put-option", "premium", "moneyness"],
  },
  premium: {
    term: "Premium",
    def: "The price you pay (to buy) or receive (to sell) for an option, quoted per share — so a $2.50 premium costs $250 for one 100-share contract. When you BUY an option, the premium is the most you can lose.",
    example: "Buy one call at a $2.50 premium and you've paid $250 and risked exactly that.",
    related: ["strike", "intrinsic-value", "extrinsic-value", "max-loss"],
  },
  "intrinsic-value": {
    term: "Intrinsic value",
    def: "The part of an option's premium that is real, exercise-it-right-now value: how far in-the-money it is. A $105 call with the stock at $112 has $7 of intrinsic value. Out of the money, intrinsic value is zero.",
    example: "Stock at $112, a $105 call: $7 is intrinsic; anything above $7 in the premium is time value.",
    related: ["extrinsic-value", "premium", "moneyness"],
  },
  "extrinsic-value": {
    term: "Extrinsic (time) value",
    def: "The rest of the premium beyond intrinsic value — what you pay for the time and uncertainty left before expiry. It melts toward zero as expiry nears (time decay) and shrinks when implied volatility falls.",
    example: "An at-the-money option is ALL time value — there's no intrinsic value to fall back on.",
    related: ["intrinsic-value", "time-decay", "implied-volatility"],
  },
  moneyness: {
    term: "Moneyness (ITM / ATM / OTM)",
    def: "Where the stock sits versus the strike. In-the-money (ITM) = the option has intrinsic value; at-the-money (ATM) = stock ≈ strike; out-of-the-money (OTM) = no intrinsic value yet, all hope and time value.",
    example: "Stock $100: a $90 call is ITM, a $100 call is ATM, a $110 call is OTM.",
    related: ["strike", "intrinsic-value", "delta"],
  },
  "break-even": {
    term: "Break-even",
    def: "The stock price at which a trade's profit is exactly zero at expiry — below/above it you lose, beyond it you win. For a long call it's the strike plus the premium you paid.",
    example: "A $105 call bought for $2.50 breaks even at $107.50 at expiry.",
    related: ["payoff-diagram", "premium", "strike"],
  },
  "max-loss": {
    term: "Max loss",
    def: "The worst case for a position. For an option you BUY it's just the premium — defined risk. For strategies that SELL options the loss can be much larger, which is exactly why the fund only ever buys.",
    example: "Long a call for $250, your max loss is $250 no matter how far the stock falls.",
    related: ["premium", "payoff-diagram", "covered-call"],
  },
  "payoff-diagram": {
    term: "Payoff diagram",
    def: "The picture of a trade's profit or loss across every possible stock price. The flat parts, the kinks at the strikes, and where the line crosses zero (break-even) tell you the whole risk-and-reward shape at a glance.",
    example: "A long call's payoff is a flat loss up to the strike, then a 45° line climbing into profit.",
    related: ["break-even", "max-loss", "long-call"],
  },
  "time-decay": {
    term: "Time decay (theta)",
    def: "Options lose a little value every day just from time passing, because there's less chance left for a big move. The bleed accelerates as expiry approaches. You can be right on direction and still lose if the move is too slow.",
    example: "Hold an at-the-money option over a quiet week and it's worth less Friday than Monday, stock unchanged.",
    related: ["theta", "extrinsic-value", "expiry"],
  },
  delta: {
    term: "Delta",
    def: "How much an option's premium moves per $1 move in the stock — and a rough gauge of the odds it finishes in-the-money. A 0.50 delta call gains ~50¢ for a $1 rise; deep-in-the-money options approach 1.00.",
    example: "A 0.30-delta call is ~30% likely to expire ITM and moves ~30¢ per $1 of stock.",
    related: ["gamma", "moneyness", "greeks"],
  },
  gamma: {
    term: "Gamma",
    def: "How fast delta itself changes as the stock moves — the option's acceleration. Highest for at-the-money options near expiry, which is what makes those swing so violently.",
    example: "High gamma means a small stock move can flip a near-the-money option from sleepy to fast-moving.",
    related: ["delta", "greeks", "gamma-exposure"],
  },
  theta: {
    term: "Theta",
    def: "The dollar amount an option loses per day from time decay, all else equal. It's negative for anything you buy — the daily rent you pay for holding the bet.",
    example: "A theta of −$5 means the position bleeds about $5 a day if nothing else changes.",
    related: ["time-decay", "vega", "greeks"],
  },
  vega: {
    term: "Vega",
    def: "How much an option's premium changes when implied volatility moves one percentage point. Buyers are long vega — they profit if the market starts pricing in bigger swings, and lose if it calms down.",
    example: "Vega of $8 means +1 point of IV adds about $8 to the position's value.",
    related: ["implied-volatility", "theta", "greeks"],
  },
  greeks: {
    term: "The Greeks",
    def: "The handful of sensitivities that describe how an option's price reacts: delta (to the stock), gamma (to delta itself), theta (to time), and vega (to volatility). Together they're the dashboard for any option position.",
    example: "Reading the Greeks tells you what your position will do before the stock even moves.",
    related: ["delta", "gamma", "theta", "vega"],
  },
  expiry: {
    term: "Expiry",
    def: "The date an option contract dies. At expiry it's worth only its intrinsic value — anything in-the-money settles for that, anything out-of-the-money expires worthless. The deadline your thesis is racing against.",
    example: "An OTM call still OTM at expiry simply vanishes — premium gone, lesson learned.",
    related: ["time-decay", "intrinsic-value", "strike"],
  },
  "covered-call": {
    term: "Covered call",
    def: "Owning 100 shares and selling a call against them to collect premium as income. The catch: if the stock rallies past the strike your shares get called away, so you cap your upside in exchange for the cash now.",
    example: "Own 100 shares at $100, sell a $110 call for $2: you pocket $200 but give up gains above $110.",
    related: ["cash-secured-put", "call-option", "premium"],
  },
  "cash-secured-put": {
    term: "Cash-secured put",
    def: "Selling a put while holding enough cash to buy the shares if assigned. You collect premium up front; if the stock falls below the strike you buy it (cushioned by the premium), otherwise you keep the premium free.",
    example: "Sell a $95 put on a $100 stock for $2: you're paid $200 to maybe buy it at $95.",
    related: ["covered-call", "put-option", "premium"],
  },

  // ---- Short selling: the Short Lab (docs/SHORT-LAB.md) ----
  "short-selling": {
    term: "Short selling",
    def: "Borrowing shares, selling them now, and buying them back later — a bet a stock FALLS. You profit if the price drops below where you sold, and lose if it rises. It's the trade the long-only fund can't make, and the only one whose loss has no cap.",
    example: "Short 100 shares at $50; if it drops to $40 you buy back for a $1,000 gain — if it runs to $80 you're down $3,000 and counting.",
    related: ["cost-to-borrow", "margin-call", "short-squeeze", "put-option"],
  },
  "cost-to-borrow": {
    term: "Cost to borrow",
    def: "The annualized fee you pay to borrow the shares you short — small for liquid names, brutal for hard-to-borrow ones. You also pay any dividend the stock issues while you're short. Carry that bleeds you the longer you hold.",
    example: "A 20%/yr borrow on a $10,000 short costs about $5.50 a day just to keep the position on.",
    related: ["short-selling", "short-interest"],
  },
  "margin-call": {
    term: "Margin call",
    def: "Shorting runs on borrowed collateral. If the stock rises against you and your equity falls below the broker's maintenance requirement, you're force-covered — bought back at the worst possible moment, locking in the loss. This is how shorts blow up.",
    example: "A short that doubles can erase your collateral and trigger a forced buy-in before you ever choose to exit.",
    related: ["short-selling", "short-squeeze"],
  },
  "short-squeeze": {
    term: "Short squeeze",
    def: "When a heavily-shorted stock rallies, shorts rush to buy back and cover — and that buying pushes the price up further, forcing more covering. A self-feeding spike with no long-side equivalent, and the nightmare scenario for a short.",
    example: "A crowded short doubling in days as everyone scrambles to cover at once.",
    related: ["short-interest", "days-to-cover", "margin-call"],
  },
  "days-to-cover": {
    term: "Days to cover",
    def: "Short interest divided by average daily volume — roughly how many days of normal trading it would take every short to buy back. A high number means shorts are packed into a small exit, which makes a squeeze more violent.",
    example: "Days-to-cover of 8 means it'd take over a week of average volume for shorts to all cover.",
    related: ["short-interest", "short-squeeze"],
  },
};
