#!/bin/bash
# GRQ Go iOS sync — run on the MAC when you need to build.
# One-time install on the Mac:
#   scp -P 2222 camerontora@camerontora.ca:/home/camerontora/grq/scripts/grqgo-mac-sync.sh ~/bin/grqgo-sync && chmod +x ~/bin/grqgo-sync
# (or from the LAN: scp camerontora@192.168.2.34:/home/camerontora/grq/scripts/grqgo-mac-sync.sh ~/bin/grqgo-sync)
set -e

REMOTE_APP="/home/camerontora/grq/mobile"
LOCAL="$HOME/Developer/Projects/personal/grqgo-build"

# Auto-detect: use LAN when reachable, external otherwise
if nc -z -w1 192.168.2.34 22 2>/dev/null; then
  UBUNTU="camerontora@192.168.2.34"
  RSYNC_SSH="ssh"
else
  UBUNTU="camerontora@camerontora.ca"
  RSYNC_SSH="ssh -p 2222"
fi

mkdir -p "$LOCAL/ios"

echo ""
echo "┌─────────────────────────────┐"
echo "│  GRQ Go iOS Sync            │"
echo "└─────────────────────────────┘"

# ── 1. Sync package files first (must happen before npm ci) ──────────────────
echo ""
echo "▸ Syncing app.json, package.json, .env, assets/..."
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/app.json" "$LOCAL/"
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/.env"     "$LOCAL/"
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/package.json" "$LOCAL/"
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/package-lock.json" "$LOCAL/"
rsync -aq --delete -e "$RSYNC_SSH" \
  --exclude='.DS_Store' --exclude='._*' \
  "$UBUNTU:$REMOTE_APP/assets/" "$LOCAL/assets/"
echo "  ✓ app.json + package.json + .env + assets/ synced"

# ── 2. Install node_modules locally ──────────────────────────────────────────
# pod install uses use_expo_modules! which calls Node.js to resolve packages.
# Node following a symlink to a network mount is too slow and silently skips
# packages, so node_modules is installed locally on the Mac for reliable pod
# autolinking. (Same lesson as the SBCA pipeline.)
NM_HASH_FILE="$LOCAL/.grqgo_nm_hash"
NM_HASH_NOW=$(cat "$LOCAL/package.json" "$LOCAL/package-lock.json" 2>/dev/null | md5 -q || echo "")
echo ""
echo "▸ Checking node_modules..."
if [ ! -d "$LOCAL/node_modules" ] || [ "$(cat "$NM_HASH_FILE" 2>/dev/null)" != "$NM_HASH_NOW" ]; then
  echo "  package.json changed — running npm ci..."
  cd "$LOCAL" && npm ci --legacy-peer-deps 2>&1 | grep -E "^added|error" | tail -3
  echo "$NM_HASH_NOW" > "$NM_HASH_FILE"
  echo "  ✓ node_modules installed locally"
else
  echo "  ✓ node_modules up to date"
fi

# ── 3. Sync JS source ────────────────────────────────────────────────────────
# Required for Release builds: expo export:embed runs a local Metro rooted at
# grqgo-build/ and calls require.context('./app') to discover Expo Router routes.
echo ""
echo "▸ Syncing JS source..."
for dir in app components constants services; do
  rsync -aq --delete -e "$RSYNC_SSH" \
    --exclude='.DS_Store' --exclude='._*' \
    "$UBUNTU:$REMOTE_APP/$dir/" "$LOCAL/$dir/"
done
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/babel.config.js" "$LOCAL/"
rsync -aq -e "$RSYNC_SSH" "$UBUNTU:$REMOTE_APP/tsconfig.json"   "$LOCAL/"
echo "  ✓ JS source synced"

# ── 4. Sync ios/ source files ─────────────────────────────────────────────────
# Excludes everything Mac-generated: Pods, build output, xcworkspace, Podfile.lock
# (Podfile.lock lives only on the Mac — generated by pod install, never on Ubuntu)
echo ""
echo "▸ Syncing ios/..."
rsync -aq --delete -e "$RSYNC_SSH" \
  --exclude='Pods/'           \
  --exclude='build/'          \
  --exclude='*.xcworkspace'   \
  --exclude='Podfile.lock'    \
  --exclude='.xcode.env.local' \
  --exclude='.DS_Store'       \
  --exclude='._*'             \
  "$UBUNTU:$REMOTE_APP/ios/" "$LOCAL/ios/"
echo "  ✓ source files synced"

# ── 5. pod install ────────────────────────────────────────────────────────────
# Runs when: xcworkspace is missing (first time), or Podfile/properties/packages changed
POD_HASH_FILE="$LOCAL/.grqgo_pod_hash"
POD_HASH_NOW=$(cat "$LOCAL/ios/Podfile" "$LOCAL/ios/Podfile.properties.json" "$LOCAL/package.json" 2>/dev/null | md5 -q)

if [ ! -d "$LOCAL/ios/GRQGo.xcworkspace" ] || \
   [ "$(cat "$POD_HASH_FILE" 2>/dev/null)" != "$POD_HASH_NOW" ]; then
  echo ""
  echo "▸ Running pod install — grab a coffee, first run takes 20-40 min..."
  cd "$LOCAL/ios" && pod install
  echo "$POD_HASH_NOW" > "$POD_HASH_FILE"
  echo "  ✓ Pods installed"
else
  echo ""
  echo "▸ Pods up to date — skipping pod install"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "┌───────────────────────────────────────────────────────────────────────┐"
echo "│  ✓ Ready to build                                                     │"
echo "│  Open:   ~/Developer/Projects/personal/grqgo-build/ios/GRQGo.xcworkspace │"
echo "│  Metro:  ssh into Ubuntu, run: ~/grq/scripts/grq-metro.sh (port 8082) │"
echo "│  Tunnel: ssh -N -L 8081:localhost:8082 camerontora@192.168.2.34 &     │"
echo "│          (simulator then finds Metro on localhost:8081 as usual)      │"
echo "└───────────────────────────────────────────────────────────────────────┘"
echo ""
